# literally just a code test

n_embd = 16 # MuP minimum
n_layer = 2
n_head = 2

batch_size = 1
block_size = 128 # ctx_len
eval_interval = 20
grad_accum_steps = 1 # basically microbatch

lr = 3e-4
min_lr = 1e-5

max_iters = 15000
eval_iters = 20
warmup_iters = 200 

data_dir = "synth_3"
